### ISSUE TITLE
Nigh distance less than landing distance.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#101]
For [Forbes 2012, task 1](https://www.forbesflatlands.com/results-show?id_results=3&db=results2012&class=results_open) pilot Rohan Holtkamp is placed 5th but with flare-timing he's placed 11th. It is surprising that he landed at 108.886 km but was given a best distance (or nigh) of only 54.426 km. The nigh distance should always be greater than or equal to the landing distance.

**Comment by philderbeast** [comment]
He's not shown as tagging the first zone:

```
  - - - '60'
      - Rohan Holtkamp
    - zonesTag:
      - null
      - fix: 1350
        time: 2012-01-05T03:30:11Z
        lat: -33.436809
        lng: 147.989807
      - fix: 3840
        time: 2012-01-05T05:34:41Z
        lat: -33.851444
        lng: 147.939127
      - null
      - null
```
