### ISSUE TITLE
Validity is null

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#200]
With dalby 2017, task 1 the validity is null and the display is showing "Loading validity workings ..."

**Comment by philderbeast** [comment]
I'm seeing a best time for the first task of negative 21 hrs.

```
gsBestTime:
- -20.999444 h
- 2.391944 h
- 2.124167 h
- 2.607778 h
- 1.877222 
```

**Comment by philderbeast** [comment]
The `frac` field is a very large number of 308 digits and Scott Barrett gets the negative time through the speed section.

```
gsSpeed:
- - - - '19'
      - Scott Barrett
    - time: -20.999444 h
      frac: 269...825
  - - - '5'
      - Jonny Durand
    - time: 2.469444 h
      frac: 269...825

```

**Comment by philderbeast** [comment]
Scott's tagging for this task:

```
  - - - '19'
      - Scott Barrett
    - zonesTag:
      - fix: 4357
        time: 2017-04-08T03:41:25Z
        lat: -27.11418333
        lng: 151.2599
      - fix: 5514
        time: 2017-04-08T04:40:55Z
        lat: -26.82181667
        lng: 151.10853333
      - fix: 6474
        time: 2017-04-08T05:12:06Z
        lat: -26.92883333
        lng: 150.91756667
      - fix: 8183
        time: 2017-04-08T06:20:02Z
        lat: -27.15421667
        lng: 151.2551666
```
