### ISSUE TITLE
Mixed dd mm.mm format with dd.dd format for turnpoints

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#207]
When running extract-input over the Quest comp 2017, the first task failed to parse properly. It parses to an empty list of turnpoints.

```
tasks:
- taskName: Open T1
  zones:
    raw: []
    raceKind: null
    openKind: null
  speedSection:
  - 2
  - 5
...
- taskName: Open T2
  zones:
    raw:
    - zoneName: QUEST
      lat: 28.53303
      lng: -81.84667
      radius: 400.0 m
      give: 398.0 m
      alt: 37.000 m
    - zoneName: QUEST
      lat: 28.53303
      lng: -81.84667
      radius: 3000.0 m
      give: 2985.0 m
      alt: 37.000 m
    - zoneName: TURN33
      lat: 28.71518
      lng: -81.8967
      radius: 5000.0 m
      give: 5025.0 m
      alt: 37.000 m
    - zoneName: T50471
      lat: 28.55515
      lng: -82.05453
      radius: 400.0 m
      give: 402.0 m
      alt: 37.000 m
    - zoneName: PANOLK
      lat: 28.77283
      lng: -82.13307
      radius: 1000.0 m
      give: 1005.0 m
      alt: 37.000 m
    - zoneName: CHERYL
      lat: 28.67143
      lng: -82.08718
      radius: 400.0 m
      give: 402.0 m
      alt: 37.000 m
    - zoneName: CHERYL
      lat: 28.67143
      lng: -82.08718
      radius: 400.0 m
      give: 398.0 m
      alt: 37.000 m
    raceKind:
      prolog:
      - cylinder:
          center:
          - 28.53303000 deg
          - -81.84667000 deg
          radius: 400.0 m
      race:
      - cylinder:
          center:
          - 28.53303000 deg
          - -81.84667000 deg
          radius: 3000.0 m
      - cylinder:
          center:
          - 28.71518000 deg
          - -81.89670000 deg
          radius: 5000.0 m
      - cylinder:
          center:
          - 28.55515000 deg
          - -82.05453000 deg
          radius: 400.0 m
      - cylinder:
          center:
          - 28.77283000 deg
          - -82.13307000 deg
          radius: 1000.0 m
      race-ess:
        cylinder:
          center:
          - 28.67143000 deg
          - -82.08718000 deg
          radius: 400.0 m
      epilog: []
      goal:
        circle:
          center:
          - 28.67143000 deg
          - -82.08718000 deg
          radius: 400.0 m
    openKind: null
  speedSection:
  - 2
  - 6
```

The relevant section from the *.fsdb file showing unusual encoding of latitude and longitude. The first task looks like it is using dd mm.mm format and the second task is using dd.dd format.

```
        <FsTaskDefinition ss="2" es="5" goal="CIRCLE" groundstart="0">
          <FsTurnpoint id="QUEST" lat="28 31.982" lon="-81 50.800" radius="400" />
          <FsTurnpoint id="QUEST" lat="28 31.982" lon="-81 50.800" radius="3000" />
          <FsTurnpoint id="T98471" lat="28 14.880" lon="-82 03.380" radius="1000" />
          <FsTurnpoint id="T7598" lat="28 31.397" lon="-82 14.220" radius="7000" />
          <FsTurnpoint id="QUEST" lat="28 31.982" lon="-81 50.800" radius="400" />
          <FsTurnpoint id="QUEST" lat="28 31.982" lon="-81 50.800" radius="400" />
        </FsTaskDefinition
...
       <FsTaskDefinition ss="2" es="6" goal="CIRCLE" groundstart="0">
          <FsTurnpoint id="QUEST" lat="28.53303" lon="-81.84667" radius="400" />
          <FsTurnpoint id="QUEST" lat="28.53303" lon="-81.84667" radius="3000" />
          <FsTurnpoint id="TURN33" lat="28.71518" lon="-81.8967" radius="5000" />
          <FsTurnpoint id="T50471" lat="28.55515" lon="-82.05453" radius="400" />
          <FsTurnpoint id="PANOLK" lat="28.77283" lon="-82.13307" radius="1000" />
          <FsTurnpoint id="CHERYL" lat="28.67143" lon="-82.08718" radius="400" />
          <FsTurnpoint id="CHERYL" lat="28.67143" lon="-82.08718" radius="400" />
        </FsTaskDefinition>
```
