### ISSUE TITLE
Jeff Kannard is getting all of the leading points.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#226]
In [Quest 2016, task 4](https://airtribune.com/qao2016/results/task1420/day/open-class) Jeff Kannard is getting all of the leading points in flare-timing but he places last and gets none of the leading points in the official results.

**Comment by philderbeast** [comment]
The leading point graph is very skewed and of the leading coefficients, I note that Yoko's is very high. Here's the abbreviated table with the first three rows and the last three rows only.

Coefficent | Fraction | Name
-- | -- | --
26.790 | 1.000 | Jeff Kannard
37.756 | 0.000 | Jeffery Bohl
43.507 | 0.000 | Robin Hamilton
47.687 | 0.000 | Peter Kelley
48.614 | 0.000 |Bill Vickery
245.329 | 0.000 |Yoko Isomoto

**Comment by philderbeast** [comment]
Jeff is shown as flying a day earlier, looking at `.flare-timing/align-time/task-4/*.csv`:

Jeff Kannard
```csv
fixIdx,time,...
1,2016-05-09T18:09:04Z,...
2,2016-05-09T18:09:35Z,...
3,2016-05-09T18:10:06Z,...
```

Robin Hamilton
```csv
fixIdx,time,...
1,2016-05-10T17:24:15Z,...
2,2016-05-10T17:24:46Z,...
3,2016-05-10T17:25:16Z,...
```

Jonny Durand
```csv
fixIdx,time,...
16,2016-05-10T17:30:40Z,...
17,2016-05-10T17:30:50Z,...
18,2016-05-10T17:31:00Z,...
```

**Comment by philderbeast** [comment]
For task 4, the first start and first lead are outside the task open close window in `*.mask-lead.yaml`.

```yaml
- openTask: 2016-05-10T18:00:00Z
  closeTask: 2016-05-11T00:00:00Z
  firstStart: 2016-05-09T18:28:44.208533942679Z
  firstLead: 2016-05-09T18:28:44.208533942679Z
  lastArrival: 2016-05-10T21:59:11.369242513968
```
