### ISSUE TITLE
For Greda 2018, the arrival weight should be zero as it is a PG comp.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#23]
For Greda 2018, the arrival weight should be zero as it is a PG comp.

```
- goalRatio: 0.571428
  weight:
    distance: 0.39839067
    leading: 0.10528163
    arrival: 7.520116e-2
    time: 0.42112653
```
