### ISSUE TITLE
Write the leading area to the working.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#246]
Write the leading area to the working file output from `mask-track`.

**Comment by philderbeast** [comment]
The area field was dded in #250 and the functionality now exists. Here's a snippet from the `mask-track` output for Dalby 2017.

```yaml
leadRank:
- - - - '19'
      - Scott Barrett
    - area: 43640933.6899 km^2 s
      coef: 2.44585821
      frac: 1
  - - - '25'
      - Hagen Bruggemann
    - area: 44455046.4149 km^2 s
      coef: 2.4914852
      frac: 0.90523003
```
