### ISSUE TITLE
Gordon takes 78 hours to complete the task.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#249]
For [Forbes 2018, task 4](https://www.forbesflatlands.com/results-show?id_results=7&db=results2018&class=results_open) Gordon is shown as taking `78:12:03` to complete the speed section.

**Comment by philderbeast** [comment]
```
  - - - '8'
      - Gordon Rigg
    - zonesTag:
      - inter:
          fixFrac: 3986.2772226294564
          time: 2018-01-02T01:51:27.277222629456Z
          lat: -33.35878977
          lng: 147.93068895
        cross:
          crossingPair:
          - fix: 3986
            time: 2018-01-02T01:51:27Z
            lat: -33.35876667
            lng: 147.93071667
          - fix: 3987
            time: 2018-01-02T01:51:28Z
            lat: -33.35885
            lng: 147.93061667
          inZone:
          - true
          - false
      - inter:
          fixFrac: 5429.088251762836
          time: 2018-01-02T02:15:41.088251762836Z
          lat: -33.29201566
          lng: 148.00898914
        cross:
          crossingPair:
          - fix: 5429
            time: 2018-01-02T02:15:41Z
            lat: -33.29203333
            lng: 148.00898333
          - fix: 5430
            time: 2018-01-02T02:15:42Z
            lat: -33.29183333
            lng: 148.00905
          inZone:
          - true
          - false
      - inter:
          fixFrac: 27471.389261229455
          time: 2018-01-05T08:27:03.389261229453Z
          lat: -30.7666509
          lng: 150.71389732
        cross:
          crossingPair:
          - fix: 27471
            time: 2018-01-05T08:27:03Z
            lat: -30.76668333
            lng: 150.7138
          - fix: 27472
            time: 2018-01-05T08:27:04Z
            lat: -30.7666
            lng: 150.71405
          inZone:
          - false
          - true
```
