### ISSUE TITLE
Loading null validity workings.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#252]
With [Dalby 2017, task 1](http://www.williamolive.com/dalby/2017/open%20class/day-one-task-result.html) the server is returning null validity and `Loading validity workings ...` is shown in the user interface.

**Comment by philderbeast** [comment]
I'm seeing a negative best time for this task:

```yaml
ssBestTime:
- 2.462907 h
- 2.369484 h
- 2.113375 h
- 2.592486 h
- 1.872238 h
gsBestTime:
- -20.999553 h
- 2.391771 h
- 2.124067 h
- 2.607669 h
- 1.876165 h
```

**Comment by philderbeast** [comment]
The pilot with the negative time for the speed section from a start gate is Scott Barrett:

```yaml
ssSpeed:
- - - - '5'
      - Jonny Durand
    - time: 2.462907 h
      frac: 1
  - - - '19'
      - Scott Barrett
    - time: 2.643249 h
      frac: 0.76363544
gsSpeed:
- - - - '19'
      - Scott Barrett
    - time: -20.999553 h
      frac: 0
  - - - '5'
      - Jonny Durand
    - time: 2.469229 h
      frac: 0
```
