### ISSUE TITLE
Jeffery Bohl tagging has not been registered?

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#290]
Jeffery Bohl is shown as flying 37.666 km in flare-timing compared to 83.483 km with FS in [Quest 2016, task 4](https://airtribune.com/qao2016/results/task1420/day/open-class). It looks like turnpoints tagged have not be marked as tagged looking at the map.

<img width="424" alt="Screen Shot 2019-07-09 at 7 08 53 AM" src="https://user-images.githubusercontent.com/633283/60883751-08617e80-a219-11e9-960a-6c63d6d6157a.png">

**Comment by philderbeast** [comment]
```yaml
  - - - '116'
      - Jeffery Bohl
    - zonesCrossSelected:
      - null
      - null
      - crossingPair:
        - fix: 1803
          time: 2016-05-10T19:11:34Z
          lat: 28.64566667
          lng: -82.21476667
          alt: 757
        - fix: 1804
          time: 2016-05-10T19:11:35Z
          lat: 28.6458
          lng: -82.21495
          alt: 755
        inZone:
        - false
        - true
      - crossingPair:
        - fix: 3926
          time: 2016-05-10T20:58:21Z
          lat: 28.71355
          lng: -81.89293333
          alt: 804
        - fix: 3927
          time: 2016-05-10T20:58:22Z
          lat: 28.7137
          lng: -81.89301667
          alt: 802
        inZone:
        - false
        - true
      - null
      zonesCrossNominees:
      - []
      - []
      - - crossingPair:
          - fix: 1803
            time: 2016-05-10T19:11:34Z
            lat: 28.64566667
            lng: -82.21476667
            alt: 757
          - fix: 1804
            time: 2016-05-10T19:11:35Z
            lat: 28.6458
            lng: -82.21495
            alt: 755
          inZone:
          - false
          - true
        - crossingPair:
          - fix: 1813
            time: 2016-05-10T19:12:01Z
            lat: 28.6489
            lng: -82.21961667
            alt: 702
          - fix: 1814
            time: 2016-05-10T19:12:04Z
            lat: 28.6493
            lng: -82.22018333
            alt: 693
          inZone:
          - true
          - false
      - - crossingPair:
          - fix: 3926
            time: 2016-05-10T20:58:21Z
            lat: 28.71355
            lng: -81.89293333
            alt: 804
          - fix: 3927
            time: 2016-05-10T20:58:22Z
            lat: 28.7137
            lng: -81.89301667
            alt: 802
          inZone:
          - false
          - true
        - crossingPair:
          - fix: 3937
            time: 2016-05-10T20:58:50Z
            lat: 28.71335
            lng: -81.8936
            alt: 802
          - fix: 3938
            time: 2016-05-10T20:58:53Z
            lat: 28.71333333
            lng: -81.89313333
            alt: 804
          inZone:
          - true
          - false
        - crossingPair:
          - fix: 3951
            time: 2016-05-10T20:59:32Z
            lat: 28.71671667
            lng: -81.89255
            alt: 782
          - fix: 3952
            time: 2016-05-10T20:59:35Z
            lat: 28.71671667
            lng: -81.89311667
            alt: 778
          inZone:
          - false
          - true
        - crossingPair:
          - fix: 3983
            time: 2016-05-10T21:01:09Z
            lat: 28.71678333
            lng: -81.89315
            alt: 753
          - fix: 3984
            time: 2016-05-10T21:01:12Z
            lat: 28.71673333
            lng: -81.89271667
            alt: 749
          inZone:
          - true
          - false
        - crossingPair:
          - fix: 3988
            time: 2016-05-10T21:01:24Z
            lat: 28.7159
            lng: -81.89263333
            alt: 765
          - fix: 3989
            time: 2016-05-10T21:01:27Z
            lat: 28.716
            lng: -81.89351667
            alt: 770
          inZone:
          - false
          - true
        - crossingPair:
          - fix: 3990
            time: 2016-05-10T21:01:30Z
            lat: 28.71635
            lng: -81.89316667
            alt: 773
          - fix: 3991
            time: 2016-05-10T21:01:33Z
            lat: 28.71658333
            lng: -81.89251667
            alt: 774
          inZone:
          - true
          - false
        - crossingPair:
          - fix: 4045
            time: 2016-05-10T21:04:17Z
            lat: 28.71776667
            lng: -81.89345
            alt: 843
          - fix: 4046
            time: 2016-05-10T21:04:20Z
            lat: 28.71748333
            lng: -81.89376667
            alt: 837
          inZone:
          - false
          - true
        - crossingPair:
          - fix: 4112
            time: 2016-05-10T21:07:39Z
            lat: 28.71845
            lng: -81.89798333
            alt: 1125
          - fix: 4113
            time: 2016-05-10T21:07:42Z
            lat: 28.71871667
            lng: -81.8976
            alt: 1122
          inZone:
          - true
          - false
        - crossingPair:
          - fix: 4113
            time: 2016-05-10T21:07:42Z
            lat: 28.71871667
            lng: -81.8976
            alt: 1122
          - fix: 4114
            time: 2016-05-10T21:07:46Z
            lat: 28.71848333
            lng: -81.89726667
            alt: 1125
          inZone:
          - false
          - true
        - crossingPair:
          - fix: 4126
            time: 2016-05-10T21:08:22Z
            lat: 28.71803333
            lng: -81.89845
            alt: 1159
          - fix: 4127
            time: 2016-05-10T21:08:25Z
            lat: 28.71856667
            lng: -81.89866667
            alt: 1165
          inZone:
          - true
          - false
      - []
      zonesCrossExcluded: []
```
