### ISSUE TITLE
Crossing of start cylinder is missed

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#318]
![Screen Shot 2019-11-17 at 8 26 43 PM](https://user-images.githubusercontent.com/633283/69018309-b6c0c180-0979-11ea-9215-d0bcd48a168f.png)

For task 3 at greda 2018, 026-Dušan Durkovič is shown as not crossing the start cylinder.

**Comment by philderbeast** [comment]
Looking at the previous deployment map, scored with flare-timing at v0.20, I can see that this pilot jumped the gun.

![Screen Shot 2019-11-18 at 8 49 17 AM](https://user-images.githubusercontent.com/633283/69057954-abed4780-09e0-11ea-9cdd-45dec3742535.png)

**Comment by philderbeast** [comment]
![crossing-early](https://user-images.githubusercontent.com/633283/69059851-3aaea280-0a7b-11ea-97d2-bab32d5082ba.png)

FS shows this pilot crossing early too looking at the map. The points that FS picks for the crossing are both outside the 2nd turnpoint, both outside the start cylinder.

```
Tp 2 G35 3000m 13:00-16:00
	1:00:00 PM: point 723 -> 724 (exit, 1:00:00 PM -> 1:00:05 PM)
```

The points on either side of this turnpoint, the crossing points are the pair (722, 723), those within the red hightlight box I've drawn over the map.

**Comment by philderbeast** [comment]
This is the last crossing of the start cylinder that flare-timing is rejecting, putting it in the excluded list:

```yaml
        - crossingPair:
          - fix: 712
            time: 2018-05-27T10:59:55Z
            lat: 43.83343333
            lng: 16.62605
            alt: 0
          - fix: 713
            time: 2018-05-27T11:00:00Z
            lat: 43.83331667
            lng: 16.6255
            alt: 0
          inZone:
          - true
          - false
```

Looking at that `*.igc` file with line numbers, it seems also that FS is showing the line number of the fix in the file, not its sequence number in the order of B records in the file.

![Screen Shot 2019-11-18 at 9 32 09 AM](https://user-images.githubusercontent.com/633283/69060998-5f0c6f80-09e6-11ea-8f21-8396c664d3db.png)

```
B1059554350006N01637563EA0000001376
 ^^^^^^ 10:59:55

B1100004349999N01637530EA0000001371
 ^^^^^^ 11:00:00
```

The first B record in the file starts on line number 11.

![Screen Shot 2019-11-18 at 9 35 42 AM](https://user-images.githubusercontent.com/633283/69061286-d6da9a00-09e6-11ea-8aa2-56b323715b7c.png)
