### ISSUE TITLE
Huge negative mean in reach stats.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#331]
With no tracklogs, reach stats are reported with a huge negative mean.

```yaml
bolster:
- max: 0.000000 km
  mean: -269653970229347386159395778618353710042696546841345985910145121736599013708251444699062715983611304031680170819807090036488184653221624933739271145959211186566651840137298227914453329401869141179179624428127508653257226023513694322210869665811240855745025766026879447359920868907719574457253034494436336205824.000000
    km
  stdDev: 0.000000 km
reach:
- max: 0.000000 km
  mean: -269653970229347386159395778618353710042696546841345985910145121736599013708251444699062715983611304031680170819807090036488184653221624933739271145959211186566651840137298227914453329401869141179179624428127508653257226023513694322210869665811240855745025766026879447359920868907719574457253034494436336205824.000000
    km
  stdDev: 0.000000 km
reachRank:
- []
nigh:
- []
```
