### ISSUE TITLE
Scaling tweaks are null.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#333]
With forbes 2012 the scaling tweaks are null but for forbes 2014 they are zero.

```yaml
compTweak:
  arrivalWeightScaling: null
  leadingWeightScaling: null

compTweak:
  arrivalWeightScaling: 0
  leadingWeightScaling: 0
```
