### ISSUE TITLE
Zero effort points for Tullio Gervasoni.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#346]
With italy 2019, task 2 Tullio Gervasoni is being awarded 0 effort points in flare-timing but 275.2 in FS for a landing at 130.4 km.

**Comment by philderbeast** [comment]
The last two zones don't seem to be tagged.

![Screen Shot 2019-12-03 at 10 08 48 AM](https://user-images.githubusercontent.com/633283/70062898-ef38e000-15b4-11ea-9373-0e1613031caa.png)

**Comment by philderbeast** [comment]
The pilot's landout for task 2:

```yaml
- - chunk: 0
    startChunk: 0.0 km
    endChunk: 0.1 km
    endAhead: 4.9 km
    down: 1
    downs:
    - 0.000 km
    downers:
    - - '66'
      - Tullio Gervasoni
    downward: 2
    rel: 2.5006e-4
    frac: 2.5006e-4
```
