### ISSUE TITLE
Is the start expected to be an exit?

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#380]
Task 1 of Chamousset 2019 has a sequence of exit, enter, enter ... zone crossings on task but it looks like flare-timing is expecting the start to be an exit with many reported as jumping the gun.

![Screen Shot 2020-03-22 at 8 41 48 AM](https://user-images.githubusercontent.com/633283/77249765-d747a380-6c19-11ea-9cd1-f107bae36ebf.png)

```yaml
 - - - '6'
      - Charles CAZAUX
    - zonesTag:
      - inter:
          fixFrac: 79.47633663792723
          time: 2019-05-26T10:32:54.476336637927Z
          lat: 45.54944285
          lng: 6.10515873
          alt: 825.48
        cross:
          crossingPair:
          - fix: 79
            time: 2019-05-26T10:32:54Z
            lat: 45.54946667
            lng: 6.10516667
            alt: 825
          - fix: 80
            time: 2019-05-26T10:32:55Z
            lat: 45.54941667
            lng: 6.10515
            alt: 826
          inZone:
          - true
          - false
      - inter:
          fixFrac: 3234.3820656479775
          time: 2019-05-26T11:25:29.382065647977Z
          lat: 45.52558577
          lng: 6.06626179
          alt: 1519.24
        cross:
          crossingPair:
          - fix: 3234
            time: 2019-05-26T11:25:29Z
            lat: 45.52556667
            lng: 6.0663
            alt: 1520
          - fix: 3235
            time: 2019-05-26T11:25:30Z
            lat: 45.52561667
            lng: 6.0662
            alt: 1518
          inZone:
          - true
          - false
```

**Comment by philderbeast** [comment]
After the fix, the first 3 taggings when the start gate is at `2019-05-26T11:45`.

```yaml
  - - - '6'
      - Charles CAZAUX
    - zonesTag:
      - inter:
          fixFrac: 79.47633663792723
          time: 2019-05-26T10:32:54.476336637927Z
          lat: 45.54944285
          lng: 6.10515873
          alt: 825.48
        cross:
          crossingPair:
          - fix: 79
            time: 2019-05-26T10:32:54Z
            lat: 45.54946667
            lng: 6.10516667
            alt: 825
          - fix: 80
            time: 2019-05-26T10:32:55Z
            lat: 45.54941667
            lng: 6.10515
            alt: 826
          inZone:
          - true
          - false
      - inter:
          fixFrac: 4432.093483475185
          time: 2019-05-26T11:45:27.093483475185Z
          lat: 45.5285151
          lng: 6.07038069
          alt: 1526.91
        cross:
          crossingPair:
          - fix: 4432
            time: 2019-05-26T11:45:27Z
            lat: 45.52851667
            lng: 6.07036667
            alt: 1527
          - fix: 4433
            time: 2019-05-26T11:45:28Z
            lat: 45.5285
            lng: 6.07051667
            alt: 1526
          inZone:
          - false
          - true
      - inter:
          fixFrac: 4859.580695455606
          time: 2019-05-26T11:52:34.580695455605Z
          lat: 45.49637796
          lng: 6.11549571
          alt: 1137.42
        cross:
          crossingPair:
          - fix: 4859
            time: 2019-05-26T11:52:34Z
            lat: 45.49641667
            lng: 6.11546667
            alt: 1138
          - fix: 4860
            time: 2019-05-26T11:52:35Z
            lat: 45.49635
            lng: 6.11551667
            alt: 1137
          inZone:
          - false
          - true
```
