### ISSUE TITLE
Keven Carter not tagging the start cylinder even with crossings.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#386]
For big spring 2016, task 1, Kevin Carter has no tagging of the start cylinder.

![Screen Shot 2020-04-04 at 7 02 15 AM](https://user-images.githubusercontent.com/633283/78428358-4376ce00-7642-11ea-99aa-2dd3aad5f7a7.png)

**Comment by philderbeast** [comment]
The crossing pair associated with the selected start, `1477/8`, is not the last crossing associated with the start at `2016-08-07T19:50:00Z`. That would be `1513/4`.

Why is the crossing pair `744/5` being associated both starts, starts at `2016-08-07T19:50:00Z` and at `2016-08-07T19:30:00Z`?

```yaml
     startSelected:
      - 2016-08-07T19:50:00Z
      - crossingPair:
        - fix: 1477
          time: 2016-08-07T19:54:01Z
          lat: 32.3073
          lng: -101.51108333
          alt: 2359
        - fix: 1478
          time: 2016-08-07T19:54:03Z
          lat: 32.30708333
          lng: -101.511
          alt: 2359
        inZone:
        - false
        - true
      startNominees:
      - - 2016-08-07T19:30:00Z
        - - - crossingPair:
              - fix: 1477
                time: 2016-08-07T19:54:01Z
                lat: 32.3073
                lng: -101.51108333
                alt: 2359
              - fix: 1478
                time: 2016-08-07T19:54:03Z
                lat: 32.30708333
                lng: -101.511
                alt: 2359
              inZone:
              - false
              - true
            - crossingPair:
              - fix: 1505
                time: 2016-08-07T19:54:57Z
                lat: 32.30685
                lng: -101.50913333
                alt: 2452
              - fix: 1506
                time: 2016-08-07T19:54:59Z
                lat: 32.30726667
                lng: -101.5092
                alt: 2457
              inZone:
              - true
              - false
            - crossingPair:
              - fix: 1511
                time: 2016-08-07T19:55:09Z
                lat: 32.30718333
                lng: -101.51028333
                alt: 2473
              - fix: 1512
                time: 2016-08-07T19:55:11Z
                lat: 32.30706667
                lng: -101.51016667
                alt: 2474
              inZone:
              - false
              - true
            - crossingPair:
              - fix: 1513
                time: 2016-08-07T19:55:13Z
                lat: 32.30703333
                lng: -101.50996667
                alt: 2478
              - fix: 1514
                time: 2016-08-07T19:55:15Z
                lat: 32.30713333
                lng: -101.50975
                alt: 2483
              inZone:
              - true
              - false
          - - crossingPair:
              - fix: 744
                time: 2016-08-07T19:29:13Z
                lat: 32.30628333
                lng: -101.50465
                alt: 1377
              - fix: 745
                time: 2016-08-07T19:29:15Z
                lat: 32.30666667
                lng: -101.50465
                alt: 1379
              inZone:
              - true
              - false
      - - 2016-08-07T19:50:00Z
        - - - crossingPair:
              - fix: 1477
                time: 2016-08-07T19:54:01Z
                lat: 32.3073
                lng: -101.51108333
                alt: 2359
              - fix: 1478
                time: 2016-08-07T19:54:03Z
                lat: 32.30708333
                lng: -101.511
                alt: 2359
              inZone:
              - false
              - true
            - crossingPair:
              - fix: 1505
                time: 2016-08-07T19:54:57Z
                lat: 32.30685
                lng: -101.50913333
                alt: 2452
              - fix: 1506
                time: 2016-08-07T19:54:59Z
                lat: 32.30726667
                lng: -101.5092
                alt: 2457
              inZone:
              - true
              - false
            - crossingPair:
              - fix: 1511
                time: 2016-08-07T19:55:09Z
                lat: 32.30718333
                lng: -101.51028333
                alt: 2473
              - fix: 1512
                time: 2016-08-07T19:55:11Z
                lat: 32.30706667
                lng: -101.51016667
                alt: 2474
              inZone:
              - false
              - true
            - crossingPair:
              - fix: 1513
                time: 2016-08-07T19:55:13Z
                lat: 32.30703333
                lng: -101.50996667
                alt: 2478
              - fix: 1514
                time: 2016-08-07T19:55:15Z
                lat: 32.30713333
                lng: -101.50975
                alt: 2483
              inZone:
              - true
              - false
          - - crossingPair:
              - fix: 744
                time: 2016-08-07T19:29:13Z
                lat: 32.30628333
                lng: -101.50465
                alt: 1377
              - fix: 745
                time: 2016-08-07T19:29:15Z
                lat: 32.30666667
                lng: -101.50465
                alt: 1379
              inZone:
              - true
              - false
```
