### ISSUE TITLE
Selected start not inserted into selected crossings.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#390]
For task 3, Greda 2018, the crossing for the selected start is correct but the start itself is null.

```yaml
- - - '74'
      - Nuno Filipe da Fonseca Bastos Gomes
    - zonesCrossSelected:
      - crossingPair:
        - fix: 210
          time: 2018-05-27T10:38:31Z
          lat: 43.82688333
          lng: 16.63938333
          alt: 722
        - fix: 211
          time: 2018-05-27T10:38:32Z
          lat: 43.82685
          lng: 16.63933333
          alt: 723
        inZone:
        - true
        - false
      - null
      - crossingPair:
        - fix: 2318
          time: 2018-05-27T11:13:39Z
          lat: 43.82651667
          lng: 16.61703333
          alt: 844
        - fix: 2319
          time: 2018-05-27T11:13:40Z
          lat: 43.82645
          lng: 16.617
          alt: 843
        inZone:
        - false
        - true
...
      startSelected:
      - 2018-05-27T11:00:00Z
      - crossingPair:
        - fix: 2130
          time: 2018-05-27T11:10:31Z
          lat: 43.83205
          lng: 16.62616667
          alt: 934
        - fix: 2131
          time: 2018-05-27T11:10:32Z
          lat: 43.83206667
          lng: 16.62631667
          alt: 933
        inZone:
        - false
        - true
```
