### ISSUE TITLE
Turnpoints tagged in the wrong order.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#391]
It looks like turnpoints are being tagged in the wrong order. Here it looks like `D01128` is being tagged as the pilot makes their way from `A05034` to `B21248`.

![Screen Shot 2020-04-05 at 6 56 36 AM](https://user-images.githubusercontent.com/633283/78472923-a7fd6000-770a-11ea-9077-46973d1ea26a.png)

**Comment by philderbeast** [comment]
The fix indices are not in order.

```yaml
crossing:
- - - - '61'
      - Deonir SPANCERSKI
    - zonesCrossSelected:
      - crossingPair:
        - fix: 80
          time: 2019-05-26T10:55:08Z
          lat: 45.54951667
          lng: 6.10566667
          alt: 818
        - fix: 81
          time: 2019-05-26T10:55:09Z
          lat: 45.54946667
          lng: 6.10561667
          alt: 820
        inZone:
        - true
        - false
      - crossingPair:
        - fix: 3190
          time: 2019-05-26T11:46:58Z
          lat: 45.52436667
          lng: 6.06466667
          alt: 1546
        - fix: 3191
          time: 2019-05-26T11:46:59Z
          lat: 45.52436667
          lng: 6.06481667
          alt: 1545
        inZone:
        - false
        - true
      - crossingPair:
        - fix: 3582
          time: 2019-05-26T11:53:30Z
          lat: 45.49595
          lng: 6.11466667
          alt: 1001
        - fix: 3583
          time: 2019-05-26T11:53:31Z
          lat: 45.49586667
          lng: 6.11476667
          alt: 998
        inZone:
        - false
        - true
      - crossingPair:
        - fix: 5179
          time: 2019-05-26T12:20:07Z
          lat: 45.56406667
          lng: 6.10521667
          alt: 1046
        - fix: 5180
          time: 2019-05-26T12:20:08Z
          lat: 45.5641
          lng: 6.1053
          alt: 1045
        inZone:
        - false
        - true
      - crossingPair:
        - fix: 7383
          time: 2019-05-26T12:56:51Z
          lat: 45.48576667
          lng: 6.1206
          alt: 792
        - fix: 7384
          time: 2019-05-26T12:56:52Z
          lat: 45.48571667
          lng: 6.12051667
          alt: 792
        inZone:
        - false
        - true
      - crossingPair:
        - fix: 9908
          time: 2019-05-26T13:38:56Z
          lat: 45.556
          lng: 6.30201667
          alt: 446
        - fix: 9909
          time: 2019-05-26T13:38:57Z
          lat: 45.55596667
          lng: 6.30216667
          alt: 446
        inZone:
        - false
        - true
      - crossingPair:
        - fix: 3582
          time: 2019-05-26T11:53:30Z
          lat: 45.49595
          lng: 6.11466667
          alt: 1001
        - fix: 3583
          time: 2019-05-26T11:53:31Z
          lat: 45.49586667
          lng: 6.11476667
          alt: 998
        inZone:
        - false
        - true
      - crossingPair:
        - fix: 8978
          time: 2019-05-26T13:23:26Z
          lat: 45.53375
          lng: 6.22781667
          alt: 621
        - fix: 8979
          time: 2019-05-26T13:23:27Z
          lat: 45.53381667
          lng: 6.22796667
          alt: 621
        inZone:
        - false
        - true
      - null
```
