### ISSUE TITLE
Read when the goal is a line

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#4]
When the comp inputs are extracted from `.fsdb`, please read when the goal is a line.

    <FsTaskDefinition ss="2" es="5" goal="LINE" groundstart="0">

**Comment by philderbeast** [comment]
After the fix, from [Forbes 2012](https://github.com/BlockScope/flare-timing-scores/tree/master/Forbes/2012) with added `strictZones`;

```
- taskName: Day 4
  zones:
  - zoneName: FORBES
    lat: -33.36137
    lng: 147.93207
    radius: 100.0 m
  - zoneName: FORBES
    lat: -33.36137
    lng: 147.93207
    radius: 15000.0 m
  - zoneName: MINES
    lat: -32.90223
    lng: 147.98492
    radius: 25000.0 m
  - zoneName: GOALD4
    lat: -32.46363
    lng: 148.989
    radius: 400.0 m
  strictZones:
  - cylinder:
      latlng:
      - -33.36137 deg
      - 147.93207 deg
      radius: 100.0 m
  - cylinder:
      latlng:
      - -33.36137 deg
      - 147.93207 deg
      radius: 15000.0 m
  - cylinder:
      latlng:
      - -32.90223 deg
      - 147.98492 deg
      radius: 25000.0 m
  - line:
      latlng:
      - -32.46363 deg
      - 148.989 deg
      radius: 400.0 m
```
