### ISSUE TITLE
Jonny Durand penalized 704 when it should be a bonus.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#424]
Seems that the sign of penalty points is being inverted somewhere along the way, looking at task 3, Forbes 2018.

```yaml
  penals:
  - - - '43'
      - Jonny Durand
    - adds:
      - penalty-points: -704
      muls: []
      resets: []
    - ''
```
