### ISSUE TITLE
FS extra reach zero, but no.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#444]
For Greda 2018 task 2, a stopped task, most of the differences are coming from reach where some pilots are given 0 km distance by FS but not for flare-timing.

| Pilot | Extra |
| --- | --- |
113-Zsolt Sandor | 7.107
063-Marketa Tomaskova | 5.820
040-Ivica Huljek | 2.023

**Comment by philderbeast** [comment]
```yaml
  - - - '113'
      - Zsolt Sandor
    - breakdown:
        distance: 152.6
        leading: 7.7
        arrival: 0
        time: 0
        effort: 0
        reach: 152.64
      place: '16'
      total: 160
      fractions:
        distance: 0.30673367
        leading: 0.25245902
        arrival: 0
        time: 0
        effort: 0
        reach: 0.30679557
      reach:
        extra: 0.000000 km
        flown: 6.973000 km
      landedMade: 6.891000 km
      ss: 2018-05-26T11:00:00Z
      es: null
      timeElapsed: null
      leadingArea: 5227238.0000 km^2 s
      leadingCoef: 1.75607782
  - - - '63'
      - Marketa Tomaskova
    - breakdown:
        distance: 124.8
        leading: 6.2
        arrival: 0
        time: 0
        effort: 0
        reach: 124.77
      place: '17'
      total: 131
      fractions:
        distance: 0.25085427
        leading: 0.20327869
        arrival: 0
        time: 0
        effort: 0
        reach: 0.25077885
      reach:
        extra: 0.000000 km
        flown: 5.700000 km
      landedMade: 5.700000 km
      ss: 2018-05-26T11:00:00Z
      es: null
      timeElapsed: null
      leadingArea: 5430535.0000 km^2 s
      leadingCoef: 1.82437518
  - - - '40'
      - Ivica Huljek
    - breakdown:
        distance: 41.5
        leading: 5.7
        arrival: 0
        time: 0
        effort: 0
        reach: 41.55
      place: '21'
      total: 47
      fractions:
        distance: 8.341709e-2
        leading: 0.18688525
        arrival: 0
        time: 0
        effort: 0
        reach: 8.351255e-2
      reach:
        extra: 0.000000 km
        flown: 1.898000 km
      landedMade: 1.895000 km
      ss: 2018-05-26T11:00:00Z
      es: null
      timeElapsed: null
      leadingArea: 5496175.0000 km^2 s
      leadingCoef: 1.84642663
```
