### ISSUE TITLE
Pickup the uom-plugin from hackage, not from git.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#48]
Remove the following from `stack.yaml` now that `uom-plugin-0.3.0.0` is up on hackage;

```
- location:
    git: https://github.com/blockscope/uom-plugin.git
    commit: c170a2df329fe8e40d13aea0b4299758d5079bda
  subdirs:
  - uom-plugin
  extra-dep: true
```
