### ISSUE TITLE
Enda Murphy not getting 50 points for effort.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#495]
Forbes 2014, task 2, Enda Murphy is at chunk 14.6km compared to 14.5km for FS but is given zero effort whereas FS is giving him 50 points for effort.

**Comment by philderbeast** [comment]
With Forbes 2015, task 1, Chris Czajkowski has the same chunk but is scoring zero for effort whereas FS is giving him 139.1 points.

**Comment by philderbeast** [comment]
```yaml
  - chunk: 146
    startChunk: 14.6 km
    endChunk: 14.7 km
    endAhead: 27.4 km
    down: 1
    downs:
    - 14.700 km
    downers:
    - - '36'
      - Enda Murphy
    downward: 7
    rel: 8.2899e-4
    frac: 9.033203e-2
```
