### ISSUE TITLE
Pilots with airScore data not showing scores.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#508]
Why are pilots with airScore data not showing scores?

![Screen Shot 2020-12-26 at 8 13 30 AM](https://user-images.githubusercontent.com/633283/103152097-96edf680-4752-11eb-93b7-0495ea22755f.png)

```yaml
- - - - '74'
      - Nuno Filipe Da Fonseca Bastos Gomes
    - breakdown:
        distance: 196.1078177701499
        leading: 11.04892052637932
        arrival: 0
        time: 52.08776819578822
        effort: 0.5
        reach: 0.5
      place: '1'
      total: 259.24450649231744
      fractions:
        distance: 1.0
        leading: 1.0
        arrival: 0
        time: 1.0
        effort: 1.0
        reach: 1.0
      reach:
        extra: 26.650323 km
        flown: 26.650323 km
      landedMade: null
      ss: '2018-05-27T11:00:00Z'
      es: '2018-05-27T12:27:18Z'
      timeElapsed: 1.45500 h
      leadingArea: null
      leadingCoef: 1.2680706770700199
  - - - '80'
      - Ricardo Nicolau Soares Terra De Oliveira Figueiredo
    - breakdown:
        distance: 23.581902753663815
        leading: 0
        arrival: 0
        time: 0
        effort: 0.44198895027624324
        reach: 0.060124841074166706
      place: '4'
      total: 23.581902753663815
      fractions:
        distance: 0.12024968214833341
        leading: 0.0
        arrival: 0
        time: 0.0
        effort: 0.8839779005524865
        reach: 0.12024968214833341
      reach:
        extra: 3.204693 km
        flown: 3.204693 km
      landedMade: null
      ss: '2018-05-27T11:00:00Z'
      es: null
      timeElapsed: null
      leadingArea: null
      leadingCoef: 5.0622079393106665
```
