### ISSUE TITLE
Pilots that made goal are not getting time points.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#536]
Pilots that made goal are not getting time points. Why is that?

![Screen Shot 2021-03-24 at 11 32 16 AM](https://user-images.githubusercontent.com/633283/112337834-a9fe5d00-8c94-11eb-8349-647aff59bc81.png)

**Comment by philderbeast** [comment]
Are Christian's turnpoint tags in order? Looks like he is going straight from `B27` to `A01`.

![Screen Shot 2021-03-24 at 11 58 27 AM](https://user-images.githubusercontent.com/633283/112342145-5f7edf80-8c98-11eb-9675-c01b01c7466a.png)

**Comment by philderbeast** [comment]
Christian's taggings are out of order by time and by fix:

```yaml
 - - - '105'
     - Christian Ciech
  - zonesTag:
    - inter:
        fixFrac: 4312.152176479801
        time: 2020-09-10T11:41:42.1521764798Z
    - inter:
        fixFrac: 5415.773130390066
        time: 2020-09-10T12:00:05.773130390066Z
    - inter:
        fixFrac: 6387.675688679387
        time: 2020-09-10T12:16:17.675688679386Z
    - inter:
        fixFrac: 9243.6785738024
        time: 2020-09-10T13:03:53.678573802398Z
    - inter:
        fixFrac: 10337.466985114746
        time: 2020-09-10T13:22:07.466985114746Z
    - inter:
        fixFrac: 12181.067810585819
        time: 2020-09-10T13:52:51.067810585819Z
    - inter:
        fixFrac: 9114.356015875834
        time: 2020-09-10T13:01:44.356015875833Z
    - inter:
        fixFrac: 9340.026576714132
        time: 2020-09-10T13:05:30.026576714131Z
```
