### ISSUE TITLE
Build with pier.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#58]
Try building with [pier](https://github.com/judah/pier).

**Comment by philderbeast** [comment]
We have two git dependencies and these are not yet implemented in pier https://github.com/judah/pier/issues/63.

```
- location:
    git: https://github.com/blockscope/hcoord.git
    commit: b2fb75029f0374e48caf4cbbfcfcc2fd674cb4f3 
  subdirs:
  - hcoord
  - hcoord-utm
  extra-dep: true
- location:
    git: https://github.com/haskell/fgl.git
    commit: e29503775e474b7a7cd8951b6bebcf1529b888b5
  extra-dep: true
```
